### ISSUE TITLE
6. As a player, I want to hear sounds when the ball hit wall or paddles.

### ISSUE THREAD

**Issue by PhuongDuy** [PhuongDuy/Assignment05#28]
khi bóng chạm thanh sẽ phát ra tiếng

**Comment by PhuongTrang013** [comment]
- Tìm âm thanh thích hợp cho ball (30m)
- Tham khảo tài liệu (1h)
- Chỉnh sửa mã nguồn và chạy thử (2h)
- Tổng thời gian để hoàn thành: 3h30m
